### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wilsonm21** [hydroflame521/StateFarmClient#2]
how do i use this without a user script manager or inspect because those are blocked can you make it usable by javascript: in the searchbar or by bookmarking the code

**Comment by Diivision-On-Top** [comment]
tampermonkey

**Comment by wilsonm21** [comment]
thast blocked

**Comment by hydroflame521** [comment]
the script can't be used as a bookmark or console, it isn't able to inject the client without tampermonkey api/run-at specification

**Comment by beast502512** [comment]
it wont let me see anything except for a egg

**Comment by hydroflame521** [comment]
which version are you using

**Comment by bigboy-baby** [comment]
> which version are you using

aye same bro, the map dont load. its becuase of the BABYLON.vector3() function. Assuming it's not recognizing BABYLON as an object anywhere. (On latest version)

**Comment by hydroflame521** [comment]
i just released a new update that will fix the current rendering bugs. it works now.
